# Generated by Django 4.0.10 on 2024-02-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=255, unique=True),
        ),
    ]
