# Generated by Django 4.0.10 on 2024-02-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ycms', '0002_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileentry',
            name='file',
            field=models.ImageField(upload_to='uhrmann/'),
        ),
    ]
